### ISSUE TITLE
Ambiguous dialog on lesson multihide

### ISSUE THREAD

**Issue by Michcioperz** [luk1337/TimeTable2#1]
When there are two lessons overlapping and I press-hold to hide one the dialog asks to "select class", not explaining should I choose the one I want to hide or the one I want remain.

**Comment by luk1337** [comment]
Well, I'll correct that in second.

**Comment by luk1337** [comment]
https://github.com/luk1337/TimeTable2/commit/3ac2a217b0f249e4eebf1dfc38ab6330e4b3cb3c
Let me know if you'll find any other bugs or borken strings XD

**Comment by Michcioperz** [comment]
Well you made a typo there (`wybierz lekcje`) but other than that sounds okay
Can't wait for F-droid update
